CREATE DATABASE interoperability;

create table fridge (
    id int GENERATED BY DEFAULT AS IDENTITY,
    fridge_type varchar(400),
    manufactured date,
    model varchar(400),
    price int,
    volume int,
    primary key(id)
);

create table customer (
    id int GENERATED BY DEFAULT AS IDENTITY,
    lastActive date,
    adress xml,
    phone int,
    email varchar(200),
    remarks json,
    primary key(id)
);

create table complaint (
    id int GENERATED BY DEFAULT AS IDENTITY,
    fridgeId int,
    customerId int,
    symptoms varchar(400),
    isResolved boolean,
    issueDate date,
    primary key(id),
    foreign key(fridgeId) references fridge,
    foreign key(customerId) references customer
);

create table serviceFacility (
    id int GENERATED BY DEFAULT AS IDENTITY,
    adress xml,
    phone int,
    email varchar(200),
    active boolean,
    ftype varchar(200), 
    primary key(id)
);

create table employee (
    id int GENERATED BY DEFAULT AS IDENTITY,
    facilityId int,
    salary float,
    adress xml,
    phone int,
    email varchar(200),
    etype varchar(200),
    primary key(id, facilityId),
    foreign key(facilityId) references serviceFacility
);

create table repairPart (
    partId int GENERATED BY DEFAULT AS IDENTITY,
    facilityId int,
    remarks json,
    rname varchar(200),
    price float,
    material varchar(200),
    volume float,
    primary key(partId, facilityId)
);

create table appointment (
    id int GENERATED BY DEFAULT AS IDENTITY,
    complaintId int,
    employeeId int,
    handled date,
    repairPartId int,
    serviceFacilityId int,
    rating float,
    primary key(id),
    foreign key(complaintId) references complaint,
    foreign key(employeeId, serviceFacilityId) references employee,
    foreign key(repairPartId, serviceFacilityId) references repairPart
);